
x-ollama-chat: &service-ollama
  image: ollama/ollama:0.11.3
  container_name: ollama-chat
  networks: ['chat']
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '6.0'
  ports:
    - 11434:11434
  volumes:
    - ollama:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['chat']
  volumes:
    - ollama:/root/.ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=ollama-chat:11434
  command: >
    sh -c "
      ollama pull nomic-embed-text:latest && ollama pull gpt-oss:20b
    "

services:
  qdrant-chat:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant:/qdrant/storage

  ollama-gpu:
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-gpu:
    <<: *init-ollama
    depends_on:
      - ollama-gpu

networks:
  chat:

volumes:
  ollama:
  qdrant:
