spring:
  application:
    name: spring-ai-chat
  ai:
    ollama:
      base-url: ${kdin.chat.ollama-url}
      embedding:
        model: ${kdin.chat.embedding-model}
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: azure-rest-api
        initialize-schema: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.apache.http.wire: DEBUG
kdin:
  chat:
    embedding-model: nomic-embed-text
    context-model: qwen2.5:7b
    ollama:
      url: http://localhost:11434
    qdrant:
      host: localhost
      port: 6334
      collection-name: azure-rest-api